In [1]:
#!pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pandas
#!pip install -i https://pypi.tuna.tsinghua.edu.cn/simple matplotlib
#!pip install -i https://pypi.tuna.tsinghua.edu.cn/simple seaborn
#!pip install -i https://pypi.tuna.tsinghua.edu.cn/simple numpy

In [2]:
import pandas as pd
import numpy as np

# 正则化函数
def normalize_feature(df):
    return df.apply(lambda column: (column - column.mean()) / column.std())

# 载入csv
df = normalize_feature(pd.read_csv('data1.csv',
                                   names=['square', 'bedrooms', 'price']))

# ones是n行1列的数据框，表示x0恒为1
ones = pd.DataFrame({'ones': np.ones(len(df))})
# 根据列合并数据
df = pd.concat([ones, df], axis=1)
df.head()

ones    square  bedrooms     price
0   1.0  0.130010 -0.223675  0.475747
1   1.0 -0.504190 -0.223675 -0.084074
2   1.0  0.502476 -0.223675  0.228626
3   1.0 -0.735723 -1.537767 -0.867025
4   1.0  1.257476  1.090417  1.595389

## 数据处理：获取 X 和 y

In [3]:
# [0:3]: 第0，1，2列
X_data = np.array(df[df.columns[0:3]])
# [-1]: 最后一列，reshape是为了把(47,0)变成形状(47,1)
y_data = np.array(df[df.columns[-1]]).reshape(len(df), 1)

print(X_data.shape, type(X_data))
print(y_data.shape, type(y_data))

for i in range(0,5):
    print(X_data.take(i,0))
    print(y_data.take(i))

(47, 3) <class 'numpy.ndarray'>
(47, 1) <class 'numpy.ndarray'>
[ 1.          0.13000987 -0.22367519]
0.4757468665785908
[ 1.         -0.50418984 -0.22367519]
-0.08407444031258184
[ 1.          0.50247636 -0.22367519]
0.2286257468223446
[ 1.         -0.73572306 -1.53776691]
-0.8670245252360933
[1.         1.25747602 1.09041654]
1.595389480360936


## 创建线性回归模型（数据流图）

In [4]:
import tensorflow as tf

alpha = 0.01 # 学习率 alpha
epoch = 500  # 训练全量数据集的轮数

# 用占位符定义输入数据的数据类型和形状
# 输入占位符 X，类型float，形状[47, 3]
print(X_data.shape)
X = tf.placeholder(tf.float32, X_data.shape)
# 输出占位符 y，类型float，形状[47, 1]
print(y_data.shape)
y = tf.placeholder(tf.float32, y_data.shape)

(47, 3)
(47, 1)


In [5]:
# 权重变量 W
# 1. 名称：”weights“，W在数据流图中的名称就是“weights”，通过get_variable方法就可以在数据流图中复用同名节点
# 2. 形状(3,1)
#    X_data.shape[0]: 第0维的维度数47（47个样本）
#    X_data.shape[1]: 第1维的维度数3 （3个特征）
#    因此根据第2个参数，权重变量W的形状是 (3,1)
# 3. 使用constant_initializer来初始化，初始化为全1
# tf.get_variable相比tf.variable可以从checkpoint中加载时可以快速找到这些变量的值
# 同时也支持变量的复用，单独的initializer的初始化
W = tf.get_variable("weights", (X_data.shape[1], 1), initializer=tf.constant_initializer())

Instructions for updating:
Colocations handled automatically by placer.


In [6]:
# 假设函数 h(x) = w0*x0+w1*x1+w2*x2, 其中x0恒为1
# 推理值 y_pred  形状[47,1]
y_pred = tf.matmul(X, W)

# 损失函数采用最小二乘法，y_pred - y 是形如[47, 1]的向量。
# tf.matmul(a,b,transpose_a=True) 表示：矩阵a的转置乘矩阵b，即 [1,47] X [47,1]
# tranpose_a = True表示对第一个参数做转置
# 损失函数操作 loss
loss_op = 1 / (2 * len(X_data)) * tf.matmul((y_pred - y), (y_pred - y), transpose_a=True)
# 随机梯度下降优化器 opt
opt = tf.train.GradientDescentOptimizer(learning_rate=alpha)
# 单轮训练操作 train_op: 每次执行train_op都会把所有数据训练一遍，得出W，计算W梯度值，根据梯度值更新W
train_op = opt.minimize(loss_op)

## 创建会话（运行环境）

In [11]:
# for i in range(0,5):
#    print(X_data.take(i,0))
#    print(y_data.take(i))
# print(train_op)
# print(loss_op)

In [8]:
with tf.Session() as sess:
    # 初始化全局变量
    sess.run(tf.global_variables_initializer())
    
    # 创建FileWriter实例
    writer = tf.summary.FileWriter("./summary/linear-regression-0/", sess.graph)
    
    # 开始训练模型，
    # 因为训练集较小，所以每轮都使用全量数据训练
    for e in range(1, epoch + 1):
        # 每个epoch都会执行一次train_op，由于X、Y是占位符，在这里要指定数据
        sess.run(train_op, feed_dict={X: X_data, y: y_data})
        if e % 10 == 0:
            loss, w = sess.run([loss_op, W], feed_dict={X: X_data, y: y_data})
            log_str = "Epoch %d \t Loss=%.4g \t Model: y = %.4gx1 + %.4gx2 + %.4g"
            print(log_str % (e, loss, w[1], w[2], w[0]))

    writer.close()

Epoch 10 	 Loss=0.4116 	 Model: y = 0.0791x1 + 0.03948x2 + 3.353e-10
Epoch 20 	 Loss=0.353 	 Model: y = 0.1489x1 + 0.07135x2 + -5.588e-11
Epoch 30 	 Loss=0.3087 	 Model: y = 0.2107x1 + 0.09676x2 + 3.912e-10
Epoch 40 	 Loss=0.2748 	 Model: y = 0.2655x1 + 0.1167x2 + -1.863e-11
Epoch 50 	 Loss=0.2489 	 Model: y = 0.3142x1 + 0.1321x2 + 1.77e-10
Epoch 60 	 Loss=0.2288 	 Model: y = 0.3576x1 + 0.1436x2 + -4.47e-10
Epoch 70 	 Loss=0.2131 	 Model: y = 0.3965x1 + 0.1519x2 + -8.103e-10
Epoch 80 	 Loss=0.2007 	 Model: y = 0.4313x1 + 0.1574x2 + -6.985e-10
Epoch 90 	 Loss=0.1908 	 Model: y = 0.4626x1 + 0.1607x2 + -4.936e-10
Epoch 100 	 Loss=0.1828 	 Model: y = 0.4909x1 + 0.1621x2 + -6.147e-10
Epoch 110 	 Loss=0.1763 	 Model: y = 0.5165x1 + 0.162x2 + -7.87e-10
Epoch 120 	 Loss=0.1709 	 Model: y = 0.5397x1 + 0.1606x2 + -5.821e-10
Epoch 130 	 Loss=0.1664 	 Model: y = 0.5609x1 + 0.1581x2 + -9.08e-10
Epoch 140 	 Loss=0.1625 	 Model: y = 0.5802x1 + 0.1549x2 + -9.965e-10
Epoch 150 	 Loss=0.1592 	 Model: y 